services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 4000:28017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    
  api:
    container_name: nokia_api
    build: .
    image: nokia_api:v1
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${PORT}:3000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start